server:
  port: 8898

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_TareaDiplomado
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect